/**
 * Generates docs/llms.txt — a curated map, one line per doc, path plus a
 * one-sentence description. Follows the llms.txt v2 shape (H1, blockquote, then
 * H2 link sections): an agent searches the map and follows the links, rather than
 * swallowing a concatenated corpus. Paths are repo-relative because the consumer
 * fetches by exact path (private-repo code search is unreliable).
 *
 * Runs as part of `pnpm docs:gen`; CI diff-gates the output. Never hand-edit.
 * Output is deterministic (no timestamps) so unchanged docs produce no diff.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { repoRoot } from './generators.mts'

const SKIP_DIRS = new Set(['.vitepress', '.obsidian', 'node_modules', 'dist'])
const H1_RE = /^# (.+)$/m
const MD_LINK_RE = /!?\[([^\]]+)\]\([^)]*\)/g // leading `!?` so image links `![alt](url)` reduce to `alt`, not `!alt`
const HTML_COMMENT_RE = /<!--[\s\S]*?-->/g
const FENCE_RE = /^(`{3,}|~{3,})/

function walkMarkdown(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name))
        out.push(...walkMarkdown(join(dir, entry.name)))
    }
    else if (entry.name.endsWith('.md')) {
      out.push(join(dir, entry.name))
    }
  }
  return out.sort()
}

interface DocEntry {
  path: string
  title: string
  description: string
}

function describe(absPath: string, root: string): DocEntry {
  const rawText = readFileSync(absPath, 'utf8')
  // POSIX-normalize so the output (and the section predicates that match on it) is
  // identical on Windows, where relative() would emit backslashes and trip docs:gen drift.
  const fallback = relative(root, absPath).split(sep).join('/')
  // Title (first H1) and the first prose paragraph after it: skip headings,
  // metadata bullets, blockquotes, and fences. HTML comments (multi-line
  // guidance blocks) are stripped up front so their innards never leak into
  // descriptions. Fence tracking (``` and ~~~) runs before the H1/paragraph
  // logic so markup inside a code block — including a leading block before the
  // real H1 — is never mistaken for the title nor leaked into the description.
  const text = rawText.replace(HTML_COMMENT_RE, '')
  const lines = text.split('\n')
  const paragraph: string[] = []
  let title: string | undefined
  let seenH1 = false
  let fence: string | null = null
  for (const line of lines) {
    const t = line.trim()
    const fenceMatch = FENCE_RE.exec(t)
    if (fenceMatch) {
      // Only a fence of the same character (``` vs ~~~) closes an open block. A
      // fence before any prose is skipped; an opening fence after prose ends it.
      if (fence === null) {
        if (paragraph.length > 0)
          break
        fence = fenceMatch[1]![0]!
      }
      else if (fenceMatch[1]![0] === fence) {
        fence = null
      }
      continue
    }
    if (fence !== null)
      continue
    if (!seenH1) {
      const h1 = H1_RE.exec(line)
      if (h1) {
        title = h1[1]!
        seenH1 = true
      }
      continue
    }
    const structural = t.startsWith('#') || t.startsWith('- ') || t.startsWith('* ') || /^\d+\. /.test(t) || t.startsWith('>') || t.startsWith('|')
    if (paragraph.length > 0 && (!t || structural))
      break
    if (!t || structural)
      continue
    paragraph.push(t)
  }
  let description = paragraph.join(' ').replace(MD_LINK_RE, '$1')
  if (description.length > 160)
    description = `${description.slice(0, 157)}...`
  return { path: fallback, title: title ?? fallback, description }
}

const root = repoRoot()
const docFiles = [join(root, 'README.md'), join(root, 'AGENTS.md'), ...walkMarkdown(join(root, 'docs'))]
  .filter(f => existsSync(f) && statSync(f).isFile()) // legible skip, not a raw ENOENT, if a doc root is ever removed
const entries = docFiles.map(f => describe(f, root))

// Sections must be EXHAUSTIVE — every entry lands somewhere, or the map lies
// about being an index of "every document". Leftovers get a catch-all section.
const used = new Set<string>()

function section(name: string, match: (p: string) => boolean): string {
  const hits = entries.filter(e => !used.has(e.path) && match(e.path))
  if (hits.length === 0)
    return ''
  for (const e of hits)
    used.add(e.path)
  const lines = hits.map(e => `- [${e.title}](${e.path})${e.description ? `: ${e.description}` : ''}`)
  return `## ${name}\n\n${lines.join('\n')}\n\n`
}

const projectName = (JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { name: string }).name

const llmsTxt = `# ${projectName} documentation map

> Machine-readable index of the project's documentation: the root README and
> AGENTS rulebook plus every doc under docs/. Generated by \`pnpm docs:gen\`
> (scripts/docs/gen-llms.mts) — never hand-edit. Paths are repo-relative; fetch
> them directly (private-repo code search is unreliable, exact paths are not).

${section('Overview', p => p === 'README.md')}${section('Rulebook', p => p === 'AGENTS.md')}${section('Decisions (why)', p => p.startsWith('docs/internal/decisions/') && !p.endsWith('_template.md'))}${section('Specs (what)', p => p.startsWith('docs/internal/specs/') && !p.endsWith('_template.md'))}${section('Development', p => p.startsWith('docs/internal/development/'))}${section('Templates', p => p.endsWith('_template.md'))}${section('Other docs', () => true)}`

writeFileSync(join(root, 'docs/llms.txt'), llmsTxt)
console.log(`docs/llms.txt (${entries.length} docs) regenerated`)
