// PUBLIC SITE — publishable. Keep this site free of anything internal
// (decisions, specs, infra, service topology). Deployment is a per-project
// choice — see docs/internal/development/docs-toolchain.md.
import { defineConfig } from 'vitepress'
import llmstxt from 'vitepress-plugin-llms'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { shared } from '../../.shared/config.ts'

export default withMermaid(defineConfig({
  ...shared,
  title: 'roots',
  description: 'Public documentation.',
  vite: {
    // Emits llms.txt into THIS public site's build output (dist). Separate from the
    // committed docs/llms.txt, which is the whole-repo map (README + AGENTS.md + all
    // of docs/) generated by scripts/docs/gen-llms.mts.
    // generateLLMsFullTxt is off deliberately: a concatenated corpus is in no version
    // of the llms.txt spec, and v2 is a search-the-map-then-follow-links model.
    plugins: [llmstxt({ generateLLMsFullTxt: false })],
  },
}))
