// PUBLIC SITE — publishable. Keep this site free of anything internal
// (decisions, specs, infra, service topology). Deployment is a per-project
// choice — see docs/internal/development/docs-toolchain.md.
import { defineConfig } from 'vitepress'
import llmstxt from 'vitepress-plugin-llms'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { shared } from '../../.shared/config.ts'

export default withMermaid(defineConfig({
  ...shared,
  title: 'roots',
  description: 'Public documentation.',
  vite: {
    // Emits llms.txt + llms-full.txt into THIS public site's build output (dist).
    // Separate from the committed docs/llms*.txt, which are the whole-repo corpus
    // (README + AGENTS.md + all of docs/) generated by scripts/docs/gen-llms.mts.
    plugins: [llmstxt()],
  },
}))
